<?php

include('cd.php');
ini_set('max_execution_time', '3600');
ob_start();
$CurrentUser = Authentication::Authenticate();

$ModelID = Utils::SafeIntFromQS('model_id');
$includepath = Utils::SafeIntFromQS('includepath');
$includepath = in_array($includepath, array(EXPORT_PATH_OPTION_NONE, EXPORT_PATH_OPTION_RELATIVE, EXPORT_PATH_OPTION_FULL)) ? $includepath : EXPORT_PATH_OPTION_NONE;

$Models = Model::GetModels(new ModelSearchParameters(
	is_NULL($ModelID) ? FALSE : $ModelID));
$Sets = Set::GetSets(new SetSearchParameters(
	FALSE,
	FALSE,
	is_null($ModelID) ? FALSE : $ModelID));

$CSVHeader = sprintf('"Filename","Filesize","CRC32","Path","Generated by CandyDollDB v%1$s on %2$s at %3$s :: Project website: https://code.google.com/p/candydolldb/"'.PHP_EOL,
	CANDYDOLLDB_VERSION,
	date('Y-m-d'),
	date('H:i:s'));

$outfile = 'CandyDollDB.csv';
if($ModelID && count($Models) > 0){
	$Model = $Models[0];
	$outfile = sprintf('CandyDollDB %1$s.csv',$Model->GetFullName());
}

header('Content-type: text/csv');
header(sprintf('Content-Disposition: attachment; filename="%1$s"', $outfile));

echo $CSVHeader;

/* @var $Model Model */
foreach ($Models as $Model)
{
	if($ModelID && $Model->getID() !== $ModelID)
	{ continue; }

	$SetsThisModel = Set::Filter($Sets, $Model->getID());
	if($SetsThisModel)
	{
		/* @var $Set Set */
		foreach ($SetsThisModel as $Set)
		{
			$ImagesThisSet = Image::GetImages(new ImageSearchParameters(FALSE, FALSE, $Set->getID(), FALSE, $Model->getID()));

			if($ImagesThisSet)
			{
				/* @var $Image Image */
				foreach($ImagesThisSet as $Image)
				{
					printf('%1$s,%2$s,%3$s,%4$s,%5$s',
						$Image->getExportFilename(),
						$Image->getFileSize(),
						$Image->getFileCRC32(),
						str_replace(CANDYIMAGEPATH.DIRECTORY_SEPARATOR, '', dirname($Image->getFilenameOnDisk())),
						PHP_EOL);
				}
			}
			
			$VideosThisSet = Video::GetVideos(new VideoSearchParameters(FALSE, FALSE, $Set->getID(), FALSE, $Model->getID()));
			
			if($VideosThisSet)
			{
				/* @var $Video Video */
				foreach($VideosThisSet as $Video)
				{
					printf('%1$s,%2$s,%3$s,%4$s,%5$s',
						$Video->getExportFilename(),
						$Video->getFileSize(),
						$Video->getFileCRC32(),
						str_replace(CANDYVIDEOPATH.DIRECTORY_SEPARATOR, '', dirname($Video->getFilenameOnDisk())),
						PHP_EOL);
				}
			}
			ob_flush();
			flush();
		}
		ob_flush();
		flush();
	}
	ob_flush();
	flush();
}

ob_end_flush();
flush();

exit;

?>