<?php

include('cd.php');
ini_set('max_execution_time', '3600');
ob_start();
$CurrentUser = Authentication::Authenticate();

$ModelID = Utils::SafeIntFromQS('model_id');

$Models = Model::GetModels(new ModelSearchParameters(
	is_NULL($ModelID) ? FALSE : $ModelID));
$Sets = Set::GetSets(new SetSearchParameters(
	FALSE,
	FALSE,
	is_NULL($ModelID) ? FALSE : $ModelID));


$outfile = 'CandyDollDB.csv';
if($ModelID && count($Models) > 0){
	$Model = $Models[0];
	$outfile = sprintf('CandyDollDB %1$s.csv',$Model->GetFullName());
}

header('Content-type: application/csv');
header(sprintf('Content-Disposition: attachment; filename="%1$s"', $outfile));

$xmlw = new XMLWriter();
$xmlw->openUri('php://output');
$xmlw->setIndent(TRUE);
$xmlw->setIndentString("\t");
$commentbool = FALSE;
$commentarray = array(sprintf("Generated by CandyDollDB on v%1\$s on %2\$s at %3\$s",CANDYDOLLDB_VERSION, date('Y-m-d'), date('H:i;s')),"Project website: https://code.google.com/p/candydolldb/");
$commentcount = count($commentarray);
$x = 0;
function XmlOutputModel($Model)
{
	global $xmlw, $Sets, $Dates, $commentbool,$commentarray,$x,$commentcount;

	$SetsThisModel = Set::Filter($Sets, $Model->getID());
	if($SetsThisModel)
	{
		/* @var $Set Set */
		foreach ($SetsThisModel as $Set)
		{
			$ImagesThisSet = Image::GetImages(new ImageSearchParameters(FALSE, FALSE, $Set->getID(), FALSE, $Model->getID()));

			if($ImagesThisSet)
			{
				/* @var $Image Image */
				foreach($ImagesThisSet as $Image)
				{
					if(Utils::_empty($Image->getFileCRC32()))
					{ continue; }
					if($commentbool === FALSE)
					{
						if($x < ($commentcount))
						{
							$xmlw->text(sprintf("%1\$s.%5\$s,%2\$s,%3\$s,%4\$s\,%6\$s,\n",$Image->getFileName(),$Image->getFileSize(),$Image->getFileCRC32(),str_replace(CANDYIMAGEPATH,"",dirname($Image->getFilenameOnDisk())),$Image->getFileExtension(),$commentarray[$x]));
							$x++;
						}
						else
						{ $commentbool = TRUE; }
					}
					else
					{
						$xmlw->text(sprintf("%1\$s.%5\$s,%2\$s,%3\$s,%4\$s\,\n",$Image->getFileName(),$Image->getFileSize(),$Image->getFileCRC32(),str_replace(CANDYIMAGEPATH,"",dirname($Image->getFilenameOnDisk())),$Image->getFileExtension()));
					}
				}
			$xmlw->flush();
			ob_flush();
			flush();
			unset($ImagesThisSet);
			}
		}
	}
}


/* @var $Model Model */
foreach ($Models as $Model)
{
	if($ModelID && $Model->getID() !== $ModelID)
	{ continue; }

	XmlOutputModel($Model);
}

ob_end_flush();
flush();

exit;

?>